const DEFAULT={xp:0,streak:0,lastDay:null,systems:{cardio:{done:[],mastery:null,lastReview:null}}};
let state=load(); let view={screen:'home',system:null,lesson:null,step:0,hearts:5,selected:null,checked:false,right:0,match:null,matchDone:[]};
const app=document.getElementById('app'), dock=document.getElementById('aiDock');
function load(){try{return Object.assign({},DEFAULT,JSON.parse(localStorage.getItem('firststeps:v1')||'{}'))}catch{return structuredClone(DEFAULT)}}
function save(){localStorage.setItem('firststeps:v1',JSON.stringify(state))}
function day(){return new Date().toISOString().slice(0,10)}
function daysSince(iso){if(!iso)return 0;return Math.max(0,Math.floor((Date.now()-new Date(iso+'T12:00:00').getTime())/86400000))}
function cardioData(){state.systems.cardio=state.systems.cardio||{done:[],mastery:null,lastReview:null};return state.systems.cardio}
function mastery(sys){if(sys.id!=='cardio')return null;const d=cardioData();if(d.mastery==null)return null;return Math.max(0,Math.round(d.mastery-daysSince(d.lastReview)*3.5))}
function moodFor(m){if(m==null)return 'New';if(m>=85)return 'Thriving';if(m>=68)return 'Stable';if(m>=50)return 'Restless';if(m>=30)return 'Pissed';return 'Unhinged'}
function moodLine(m){const mood=moodFor(m);return {New:'Fresh start. No grudges yet.',Thriving:'Annoyingly competent.',Stable:'We are fine. Do not ruin it.',Restless:'I noticed the silence.',Pissed:'I see we have moved on emotionally.',Unhinged:'At this point, just put the aorta in the brain.'}[mood]}
function esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
function mascot(type='heart',size=78){
  if(type==='heart'||type==='Heart'||type==='Valve'||type==='Coronary'||type==='Myocyte'){
    const extra=type==='Valve'?'<path d="M47 51q13-10 26 0" stroke="#a9324f" stroke-width="5" fill="none" stroke-linecap="round"/>':type==='Coronary'?'<path d="M60 34q-16 18-11 43m11-28q15 8 19 28" stroke="#f7c2cd" stroke-width="4" fill="none"/>':type==='Myocyte'?'<path d="M37 82h46" stroke="#a9324f" stroke-width="4" stroke-dasharray="5 4"/>':'';
    return `<svg viewBox="0 0 120 120" width="${size}" height="${size}" style="animation:float 3.3s ease-in-out infinite;overflow:visible"><path d="M60 103C18 75 14 42 34 30c12-8 22-2 26 8 4-10 14-16 26-8 20 12 16 45-26 73z" fill="#ef8399" stroke="#a9324f" stroke-width="4"/>${extra}<ellipse cx="50" cy="57" rx="4" ry="5" fill="#18322f"/><ellipse cx="70" cy="57" rx="4" ry="5" fill="#18322f"/><circle cx="51" cy="55" r="1.3" fill="white"/><circle cx="71" cy="55" r="1.3" fill="white"/><path d="M51 70q9 8 18 0" stroke="#18322f" stroke-width="3" fill="none" stroke-linecap="round"/></svg>`;
  }
  return `<div style="width:${size}px;height:${size}px;border-radius:24px;background:#e9f4ef;display:grid;place-items:center;font-size:${size*.48}px">✦</div>`;
}
function header(){return `<header class="top"><div class="brand"><h1>First Steps</h1><p>MASTER MEDICINE ONE STEP AT A TIME</p></div><div class="stats"><span class="chip">🔥 ${state.streak||0}</span><span class="chip">★ ${state.xp||0}</span></div></header>`}
function render(){if(view.screen==='home')home();else if(view.screen==='system')system();else if(view.screen==='lesson')lesson();else result()}
function home(){dock.classList.add('hidden');const cd=cardioData();app.innerHTML=header()+`
  <section class="hero"><div class="hero-row">${mascot('heart',82)}<div><h2>Your memory has a pulse.</h2><p>Learn in short steps, then come back before the system starts taking it personally.</p><button class="cta" onclick="openSystem('cardio')">${cd.done.length?'Continue Cardiology':'Start Cardiology'}</button></div></div></section>
  <div class="section-title"><h2>Systems</h2><span>Linear inside each system</span></div><div class="systems">${SYSTEMS.map(s=>systemCard(s)).join('')}</div>
  <p class="footer-note">Prototype content is currently deepest in Cardiology. Other systems are visible so the full information architecture can be tested before their curricula are expanded.</p>`}
function systemCard(s){const m=mastery(s),done=s.id==='cardio'?cardioData().done.length:0,progress=Math.round(done/s.total*100);return `<button class="system ${s.id==='cardio'?'active':''}" style="--accent:${s.accent}" onclick="openSystem('${s.id}')"><div class="system-head"><div class="sys-icon">${s.icon}</div><span class="sys-mood">${moodFor(m)}</span></div><h3>${s.name}</h3><p>${s.blurb}</p><div class="meter"><i style="width:${progress}%"></i></div><div class="small-row"><span>Progress ${progress}%</span><span>${m==null?'Mastery —':'Mastery '+m+'%'}</span></div></button>`}
window.openSystem=function(id){view.screen='system';view.system=id;view.lesson=null;window.scrollTo({top:0,behavior:'smooth'});render()}
function system(){dock.classList.add('hidden');const s=SYSTEMS.find(x=>x.id===view.system);if(s.id!=='cardio'){app.innerHTML=`<button class="back" onclick="goHome()">← All systems</button><section class="system-banner" style="--accent:${s.accent};--accent-d:${s.deep}"><div class="row"><div class="sys-icon" style="color:${s.deep}">${s.icon}</div><div><h2>${s.name}</h2><p>${s.blurb}</p></div></div></section><div class="placeholder"><h3>System shell ready</h3><p>This system is unlocked in the product architecture. The first polished curriculum pass is Cardiology; once that learning loop is approved, the same structure will be populated here.</p></div>`;return}
  const d=cardioData(),m=mastery(s),progress=Math.round(d.done.length/CARDIO.lessons.length*100);app.innerHTML=`<button class="back" onclick="goHome()">← All systems</button><section class="system-banner" style="--accent:${s.accent};--accent-d:${s.deep}"><div class="row">${mascot('heart',82)}<div><h2>${CARDIO.title}</h2><p>${CARDIO.intro}</p></div></div><div class="progress-grid"><div class="progress-card"><span>Progress</span><b>${progress}%</b></div><div class="progress-card"><span>Mastery</span><b>${m==null?'—':m+'%'}</b></div></div></section><div class="speech ${m!=null&&m<50?'joke':''}">${mascot('heart',58)}<div class="bubble"><span class="who">Heart</span>${moodLine(m)}</div></div><div class="lesson-list">${CARDIO.lessons.map((l,i)=>lessonButton(l,i,d.done)).join('')}</div>`}
function lessonButton(l,i,done){const complete=done.includes(l.id),unlocked=i===0||done.includes(CARDIO.lessons[i-1].id);return `<button class="lesson-btn ${complete?'done':''} ${!unlocked?'locked':''}" ${!unlocked?'disabled':''} onclick="startLesson('${l.id}')"><div class="lesson-num">${complete?'✓':i+1}</div><div><h3>${l.title}</h3><p>${l.subtitle}</p></div><span class="go">${unlocked?'›':'🔒'}</span></button>`}
window.goHome=function(){view.screen='home';view.system=null;render()}
window.startLesson=function(id){const l=CARDIO.lessons.find(x=>x.id===id);view={screen:'lesson',system:'cardio',lesson:id,step:0,hearts:5,selected:null,checked:false,right:0,match:null,matchDone:[]};dock.classList.remove('hidden');window.scrollTo({top:0,behavior:'smooth'});render()}
function lesson(){const l=CARDIO.lessons.find(x=>x.id===view.lesson),st=l.steps[view.step],pct=Math.round(view.step/l.steps.length*100);app.innerHTML=`<div class="lesson-top"><button class="close" onclick="exitLesson()">×</button><div class="bar"><i style="width:${pct}%"></i></div><div class="hearts">♥ ${view.hearts}</div></div><div id="stage">${stage(l,st)}</div>`;wireStage(l,st)}
window.exitLesson=function(){view.screen='system';view.system='cardio';dock.classList.add('hidden');render()}
function stage(l,st){if(st.type==='teach')return `<div class="speech">${mascot(l.character,72)}<div class="bubble"><span class="who">${l.character}</span>${esc(st.text)}</div></div><section class="card"><span class="eyebrow">Core concept</span><h2>${esc(st.title)}</h2><p>${esc(st.text)}</p>${st.pearl?`<div class="pearl"><b>Step 1 pearl</b> ${esc(st.pearl)}</div>`:''}</section><button class="action" onclick="nextStep()">Got it</button>`;
  if(st.type==='joke')return `<div class="speech joke">${mascot(l.character,90)}<div class="bubble"><span class="who">${l.character}</span>${esc(st.text)}</div></div><button class="action" onclick="nextStep()">Continue</button>`;
  if(st.type==='choice')return `<div class="speech">${mascot(l.character,62)}<div class="bubble"><span class="who">${l.character}</span>Apply the mechanism.</div></div><section class="card"><p class="question">${esc(st.q)}</p><div class="options">${st.opts.map((o,i)=>`<button class="opt" data-i="${i}">${esc(o)}</button>`).join('')}</div><div id="feedback"></div><button id="checkBtn" class="action" disabled>Check</button></section>`;
  if(st.type==='match')return `<div class="speech">${mascot(l.character,62)}<div class="bubble"><span class="who">${l.character}</span>Connect the lesion to the finding.</div></div><section class="card"><p class="question">${esc(st.q)}</p><div class="match-grid"><div class="match-col">${st.pairs.map((p,i)=>`<button class="match left" data-i="${i}">${esc(p[0])}</button>`).join('')}</div><div class="match-col">${shufflePairs(st.pairs).map(x=>`<button class="match right" data-i="${x.i}">${esc(x.text)}</button>`).join('')}</div></div><div id="feedback"></div></section>`;return ''}
function shufflePairs(pairs){const arr=pairs.map((p,i)=>({i,text:p[1]}));for(let i=arr.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[arr[i],arr[j]]=[arr[j],arr[i]]}return arr}
function wireStage(l,st){renderAI(st);if(st.type==='choice'){document.querySelectorAll('.opt').forEach(b=>b.onclick=()=>{if(view.checked)return;view.selected=+b.dataset.i;document.querySelectorAll('.opt').forEach(x=>x.classList.remove('sel'));b.classList.add('sel');document.getElementById('checkBtn').disabled=false});document.getElementById('checkBtn').onclick=checkChoice}if(st.type==='match'){view.match=null;view.matchDone=[];document.querySelectorAll('.left').forEach(b=>b.onclick=()=>pickMatch('L',b));document.querySelectorAll('.right').forEach(b=>b.onclick=()=>pickMatch('R',b))}}
function checkChoice(){if(view.checked)return;const l=CARDIO.lessons.find(x=>x.id===view.lesson),st=l.steps[view.step],ok=view.selected===st.a;view.checked=true;document.querySelectorAll('.opt').forEach(b=>{const i=+b.dataset.i;if(i===st.a)b.classList.add('good');else if(i===view.selected)b.classList.add('bad');b.disabled=true});if(ok)view.right++;else view.hearts=Math.max(0,view.hearts-1);const f=document.getElementById('feedback');f.className='feedback'+(ok?'':' bad');f.innerHTML=`<b>${ok?'Correct.':'Not quite.'}</b>${esc(st.why)}`;const btn=document.getElementById('checkBtn');btn.disabled=false;btn.textContent=view.hearts===0?'Review and exit':'Continue';btn.onclick=()=>view.hearts===0?exitLesson():nextStep()}
function pickMatch(side,b){if(b.classList.contains('ok'))return;if(side==='L'){view.match=+b.dataset.i;document.querySelectorAll('.left').forEach(x=>x.classList.remove('sel'));b.classList.add('sel');return}if(view.match==null)return;const ri=+b.dataset.i,li=view.match;if(ri===li){document.querySelector(`.left[data-i="${li}"]`).classList.add('ok');b.classList.add('ok');view.matchDone.push(li);view.match=null;document.querySelectorAll('.left').forEach(x=>x.classList.remove('sel'));if(view.matchDone.length===document.querySelectorAll('.left').length){view.right++;document.getElementById('feedback').className='feedback';document.getElementById('feedback').innerHTML='<b>All matched.</b>Build the association in both directions: lesion → finding and finding → lesion.';setTimeout(nextStep,650)}}else{b.classList.add('bad');view.hearts=Math.max(0,view.hearts-1);setTimeout(()=>b.classList.remove('bad'),400);view.match=null;document.querySelectorAll('.left').forEach(x=>x.classList.remove('sel'));if(view.hearts===0)setTimeout(exitLesson,450)}}
window.nextStep=function(){const l=CARDIO.lessons.find(x=>x.id===view.lesson);view.step++;view.selected=null;view.checked=false;if(view.step>=l.steps.length)return finishLesson(l);render();window.scrollTo({top:0,behavior:'smooth'})}
function finishLesson(l){const d=cardioData(),wasDone=d.done.includes(l.id);if(!wasDone)d.done.push(l.id);const questionCount=l.steps.filter(s=>s.type==='choice'||s.type==='match').length;const accuracy=questionCount?Math.round(view.right/questionCount*100):100;const prior=d.mastery==null?72:mastery(SYSTEMS[0]);d.mastery=Math.min(100,Math.round(prior*.55+accuracy*.45+6));d.lastReview=day();if(!wasDone)state.xp+=20+view.right*5;const y=new Date();y.setDate(y.getDate()-1);const yesterday=y.toISOString().slice(0,10);if(state.lastDay!==day()){state.streak=state.lastDay===yesterday?(state.streak||0)+1:1;state.lastDay=day()}save();view.screen='result';view.accuracy=accuracy;dock.classList.add('hidden');render()}
function result(){const l=CARDIO.lessons.find(x=>x.id===view.lesson),m=mastery(SYSTEMS[0]);app.innerHTML=`<div class="result">${mascot(l.character,135)}<h2>${view.accuracy>=90?'Clean work.':view.accuracy>=70?'Solid step.':'Needs another pass.'}</h2><p>${l.title} completed.</p><div class="score-grid"><div class="score"><span>Accuracy</span><b>${view.accuracy}%</b></div><div class="score"><span>Cardio mastery</span><b>${m}%</b></div></div><button class="action" onclick="backToCardio()">Continue</button></div>`}
window.backToCardio=function(){view.screen='system';view.system='cardio';render()}
function renderAI(st){if(view.screen!=='lesson'){dock.classList.add('hidden');return}dock.classList.remove('hidden');dock.innerHTML=`<div id="aiAnswer"></div><div class="ai-suggestions"><button onclick="askQuick('Why?')">Why?</button><button onclick="askQuick('Compare the options')">Compare the options</button><button onclick="askQuick('Give me a Step 1 example')">Step 1 example</button><button onclick="askQuick('Quiz me again')">Quiz me again</button></div><div class="ai-box"><input id="aiInput" placeholder="Ask First Steps AI…" aria-label="Ask First Steps AI"/><button onclick="askAI()">Ask</button></div>`;const input=document.getElementById('aiInput');input.onkeydown=e=>{if(e.key==='Enter')askAI()}}
window.askQuick=function(q){document.getElementById('aiInput').value=q;askAI()}
window.askAI=function(){const input=document.getElementById('aiInput'),q=(input.value||'').trim();if(!q)return;const l=CARDIO.lessons.find(x=>x.id===view.lesson);let a='';const low=q.toLowerCase();if(l.id==='hemo'&&(low.includes('preload')||low.includes('afterload')||low==='why?'))a='Preload reflects ventricular filling and end-diastolic wall stress; afterload is the load opposing ejection. Valsalva lowers venous return, which lowers preload. In HCM, the smaller LV cavity worsens dynamic outflow obstruction.';else if(l.id==='murmurs')a='Use timing + direction of abnormal flow + maneuver physiology. Valsalva lowers LV volume; squatting raises venous return and systemic vascular resistance. Those changes move MVP timing and alter HCM intensity in predictable directions.';else if(l.id==='ischemia')a='Start with the ECG territory, then map it to coronary anatomy. Inferior leads II, III and aVF classically point to RCA; anterior precordial leads point toward LAD territory.';else if(l.id==='hf')a='HFrEF is primarily impaired contraction; HFpEF is impaired relaxation/compliance. Neurohormonal compensation can help short-term perfusion but chronically increases remodeling and wall stress.';else a='Focus on the mechanism on this screen, then ask what variable changes next. That is usually more reliable than memorizing the isolated association.';if(low.includes('quiz me'))a+=' Try this: predict the direction of preload, afterload, or contractility before you look at the answer choices.';document.getElementById('aiAnswer').innerHTML=`<div class="ai-answer"><b>First Steps AI · prototype</b>${esc(a)}</div>`;input.value=''}
render();
